artifact_location: file:///C:/Users/Nikhil Singhvi/OneDrive/Desktop/Conference1/Smart_Surveillance/Smart-Surveillance-System-for-Vehicle-Crash-Detection/src/training/runs/mlflow/0
creation_time: 1770400547511
experiment_id: '0'
last_update_time: 1770400547511
lifecycle_stage: active
name: Default
